#!/usr/bin/env node

/**
 * Capstone MCP Server — HybridNotesFramework Edition
 * ====================================================
 * Connects Claude Desktop to your Selenium Java project.
 *
 * Tools exposed to Claude Desktop:
 *   1. list_project_structure   — shows all files in the project
 *   2. read_file                — reads any file by path
 *   3. write_file               — creates or overwrites a file
 *   4. generate_test_script     — generates a full Java TestNG class from plain English
 *   5. execute_tests            — runs mvn test with filters / groups / suite XML
 *   6. get_test_results         — reads Surefire + Allure results after a run
 *   7. list_test_classes        — lists all test classes in src/test/java
 *
 * ALSO exposes a plain HTTP REST endpoint (not an MCP tool) used by
 * SelfHealingLocator.java inside the Java tests:
 *   POST http://localhost:3000/suggest-locator
 *   Body:  { "failedLocator": "...", "pageHtml": "..." }
 *   Reply: { "suggestion": "css:: .btn-add" }
 *
 * The MCP protocol side talks over stdio (Claude Desktop connects to it).
 * The REST side listens on port 3000 (the Java tests connect to it).
 * Both run inside the same Node process.
 */

import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";
import { execSync } from "child_process";
import fs from "fs";
import path from "path";
import http from "http";

// ── CONFIG ────────────────────────────────────────────────────────────────────

const PROJECT_ROOT =
  process.env.PROJECT_ROOT ||
  "D:\\Sprint\\capgemini_Capstone_Project\\fixfw";

const MVN = process.env.MVN_CMD || "mvn";

// Port the Java SelfHealingLocator will POST to for locator suggestions
const HEALING_PORT = parseInt(process.env.HEALING_PORT || "3000", 10);

// ── HELPERS ───────────────────────────────────────────────────────────────────

function safeRead(filePath) {
  try { return fs.readFileSync(filePath, "utf8"); }
  catch (e) { return `ERROR reading file: ${e.message}`; }
}

function safeWrite(filePath, content) {
  try {
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    fs.writeFileSync(filePath, content, "utf8");
    return `Written: ${filePath}`;
  } catch (e) { return `ERROR writing file: ${e.message}`; }
}

function walkDir(dir, ext = "", results = [], depth = 0) {
  if (depth > 8) return results;
  try {
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
      if (["node_modules", ".git", "target", ".idea"].includes(e.name)) continue;
      const full = path.join(dir, e.name);
      if (e.isDirectory()) walkDir(full, ext, results, depth + 1);
      else if (!ext || e.name.endsWith(ext)) results.push(full);
    }
  } catch {}
  return results;
}

function runCommand(cmd, cwd) {
  try {
    const out = execSync(cmd, {
      cwd: cwd || PROJECT_ROOT,
      timeout: 300_000,
      encoding: "utf8",
      stdio: ["pipe", "pipe", "pipe"],
    });
    return { success: true, output: out };
  } catch (e) {
    return {
      success: false,
      output: (e.stdout || "") + "\n" + (e.stderr || "") + "\n" + e.message,
    };
  }
}

// ── TOOL: generate_test_script ────────────────────────────────────────────────
// Generates a Java TestNG class and writes it to the correct package.
// Packages match the fixfw project: com.notesapp.tests.*
function generateTestScript(args) {
  const {
    description,
    test_type = "ui",
    class_name,
    write_to_project = true,
  } = args;

  if (!description) return "ERROR: description is required.";
  if (!class_name)  return "ERROR: class_name is required (e.g. 'LoginNegativeV2Test').";

  const typeMap = {
    ui:  { pkg: "com.notesapp.tests.ui",  dir: "src/test/java/com/notesapp/tests/ui"  },
    api: { pkg: "com.notesapp.tests.api", dir: "src/test/java/com/notesapp/tests/api" },
    e2e: { pkg: "com.notesapp.tests.e2e", dir: "src/test/java/com/notesapp/tests/e2e" },
  };
  const { pkg, dir } = typeMap[test_type] || typeMap.ui;

  // ── UI template (extends BaseTest — gets browser lifecycle for free) ────────
  const uiTemplate = `package ${pkg};

import com.notesapp.base.BaseTest;
import com.notesapp.config.ConfigReader;
import com.notesapp.pages.NotesLoginPage;
import com.notesapp.pages.NotesPage;
import com.notesapp.utils.ScreenshotUtils;
import com.notesapp.agentic.SelfHealingLocator;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.testng.Assert;
import org.testng.annotations.Test;

/**
 * Generated by Claude MCP Server
 * Description: ${description}
 */
public class ${class_name} extends BaseTest {

    @Test(description = "${description}")
    public void ${toCamel(class_name)}() {
        resetBrowserState();

        NotesLoginPage loginPage = new NotesLoginPage(driver);
        loginPage.login(
                ConfigReader.getProperty("email"),
                ConfigReader.getProperty("password")
        );

        Assert.assertTrue(loginPage.isLoginSuccessful(),
                "Login must succeed before running: ${description}");

        // TODO: add your test-specific steps below
        // Example using self-healing locator:
        //   WebElement btn = SelfHealingLocator.find(driver,
        //       By.id("primary-id"),
        //       By.cssSelector(".fallback-class"));

        NotesPage notesPage = new NotesPage(driver);
        // notesPage.createNote("Title", "Description", "Work");
        // Assert.assertTrue(notesPage.isNoteVisible("Title"), "Note must appear");
    }
}
`;

  // ── API template ────────────────────────────────────────────────────────────
  const apiTemplate = `package ${pkg};

import com.notesapp.api.AuthAPI;
import com.notesapp.api.BaseAPI;
import com.notesapp.api.NotesAPI;
import com.notesapp.config.ConfigReader;
import io.restassured.response.Response;
import org.testng.Assert;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

/**
 * Generated by Claude MCP Server
 * Description: ${description}
 */
public class ${class_name} {

    String token;

    @BeforeClass
    public void setUp() {
        BaseAPI.setUp();
        token = AuthAPI.getToken(
                ConfigReader.getProperty("email"),
                ConfigReader.getProperty("password")
        );
        Assert.assertNotNull(token, "Token must not be null");
    }

    @Test(description = "${description}")
    public void ${toCamel(class_name)}() {
        // TODO: add your API test steps below
        // Example:
        //   Response resp = NotesAPI.getAllNotes(token);
        //   Assert.assertEquals(resp.getStatusCode(), 200);
        //   Assert.assertNotNull(resp.jsonPath().getList("data"));
    }
}
`;

  // ── E2E / Hybrid template ───────────────────────────────────────────────────
  const e2eTemplate = `package ${pkg};

import com.notesapp.api.AuthAPI;
import com.notesapp.api.BaseAPI;
import com.notesapp.api.NotesAPI;
import com.notesapp.base.BaseTest;
import com.notesapp.config.ConfigReader;
import com.notesapp.pages.NotesLoginPage;
import com.notesapp.pages.NotesPage;
import io.restassured.response.Response;
import org.testng.Assert;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

/**
 * Generated by Claude MCP Server
 * Description: ${description}
 */
public class ${class_name} extends BaseTest {

    String token;

    @BeforeClass
    public void setUpAPI() {
        BaseAPI.setUp();
        token = AuthAPI.getToken(
                ConfigReader.getProperty("email"),
                ConfigReader.getProperty("password")
        );
        Assert.assertNotNull(token, "Need a valid token for E2E tests");
    }

    @Test(description = "${description}")
    public void ${toCamel(class_name)}() {
        resetBrowserState();

        // ── Step 1: UI — Login ───────────────────────────────────────────
        NotesLoginPage loginPage = new NotesLoginPage(driver);
        loginPage.login(ConfigReader.getProperty("email"), ConfigReader.getProperty("password"));
        Assert.assertTrue(loginPage.isLoginSuccessful(), "Login must succeed");

        String noteTitle = "E2E-" + System.currentTimeMillis();
        NotesPage notesPage = new NotesPage(driver);

        // ── Step 2: UI — Create note ─────────────────────────────────────
        notesPage.createNote(noteTitle, "Created by Claude MCP E2E test", "Work");
        Assert.assertTrue(notesPage.isNoteVisible(noteTitle), "Note must appear in UI");

        // ── Step 3: API — Verify note exists ────────────────────────────
        Response apiResp = NotesAPI.getAllNotes(token);
        Assert.assertEquals(apiResp.getStatusCode(), 200);
        Assert.assertTrue(apiResp.asString().contains(noteTitle),
                "UI-created note must be visible in GET /notes API response");
    }
}
`;

  const template = test_type === "api" ? apiTemplate
                 : test_type === "e2e" ? e2eTemplate
                 : uiTemplate;

  if (write_to_project) {
    const filePath = path.join(PROJECT_ROOT, dir, `${class_name}.java`);
    const result = safeWrite(filePath, template);
    return `${result}\n\n--- Generated Java Class ---\n\n${template}`;
  }
  return `--- Preview (not written) ---\n\n${template}`;
}

// converts "LoginNegativeV2Test" → "loginNegativeV2Test" for method names
function toCamel(s) {
  return s.charAt(0).toLowerCase() + s.slice(1);
}

// ── TOOL: execute_tests ───────────────────────────────────────────────────────
function executeTests(args) {
  const { filter, suite, group, headless = true } = args || {};
  let cmd = `${MVN} clean test`;
  if (suite)    cmd += ` -Dsurefire.suiteXmlFiles=src/test/resources/${suite}`;
  if (filter)   cmd += ` -Dtest=${filter}`;
  if (group)    cmd += ` -Dgroups=${group}`;
  if (headless) cmd += ` -Dheadless=true`;
  cmd += ` -q`;
  const result = runCommand(cmd);
  return `Command: ${cmd}\n\nSuccess: ${result.success}\n\n${result.output.slice(0, 8000)}`;
}

// ── TOOL: get_test_results ────────────────────────────────────────────────────
function getTestResults(args) {
  const { format = "summary" } = args || {};
  const surefireDir = path.join(PROJECT_ROOT, "target", "surefire-reports");
  const allureDir   = path.join(PROJECT_ROOT, "target", "allure-results");
  let output = "=== Test Results ===\n\n";

  if (fs.existsSync(surefireDir)) {
    try {
      const files = fs.readdirSync(surefireDir).filter(f => f.endsWith(".xml"));
      let passed = 0, failed = 0, skipped = 0, errors = 0;
      for (const f of files) {
        const c = safeRead(path.join(surefireDir, f));
        const tests   = parseInt(c.match(/tests="(\d+)"/)?.[1]    || 0);
        const fa      = parseInt(c.match(/failures="(\d+)"/)?.[1] || 0);
        const er      = parseInt(c.match(/errors="(\d+)"/)?.[1]   || 0);
        const sk      = parseInt(c.match(/skipped="(\d+)"/)?.[1]  || 0);
        passed  += tests - fa - er - sk;
        failed  += fa;
        errors  += er;
        skipped += sk;
      }
      output += `Surefire Summary\n  Passed : ${passed}\n  Failed : ${failed + errors}\n  Skipped: ${skipped}\n\n`;
      if (format === "full") {
        for (const f of files.slice(0, 10)) {
          output += `--- ${f} ---\n${safeRead(path.join(surefireDir, f)).slice(0, 2000)}\n\n`;
        }
      }
    } catch (e) { output += `Surefire read error: ${e.message}\n`; }
  } else {
    output += "No surefire-reports found. Run tests first.\n";
  }

  if (fs.existsSync(allureDir)) {
    const count = fs.readdirSync(allureDir).filter(f => f.endsWith("-result.json")).length;
    output += `Allure result files: ${count}\n  Path: ${allureDir}\n  Run: mvn allure:serve  to open\n`;
  }
  return output;
}

// ── TOOL: list_project_structure ──────────────────────────────────────────────
function listProjectStructure(args) {
  const { ext = "", dir: subDir = "" } = args || {};
  const searchDir = subDir ? path.join(PROJECT_ROOT, subDir) : PROJECT_ROOT;
  const files = walkDir(searchDir, ext);
  return files.map(f => f.replace(PROJECT_ROOT, "").replace(/\\/g, "/")).join("\n") || "No files found.";
}

// ── TOOL: read_file ───────────────────────────────────────────────────────────
function readFile(args) {
  if (!args?.file_path) return "ERROR: file_path is required";
  const full = path.isAbsolute(args.file_path)
    ? args.file_path
    : path.join(PROJECT_ROOT, args.file_path);
  return safeRead(full);
}

// ── TOOL: write_file ──────────────────────────────────────────────────────────
function writeFile(args) {
  if (!args?.file_path) return "ERROR: file_path is required";
  if (args.content === undefined) return "ERROR: content is required";
  const full = path.isAbsolute(args.file_path)
    ? args.file_path
    : path.join(PROJECT_ROOT, args.file_path);
  return safeWrite(full, args.content);
}

// ── TOOL: list_test_classes ───────────────────────────────────────────────────
function listTestClasses() {
  const testDir = path.join(PROJECT_ROOT, "src", "test", "java");
  const files = walkDir(testDir, ".java");
  return files
    .filter(f => f.includes("Test"))
    .map(f => f.replace(PROJECT_ROOT, "").replace(/\\/g, "/"))
    .join("\n") || "No test classes found.";
}

// ── REST ENDPOINT: /suggest-locator ──────────────────────────────────────────
// Called by McpSeleniumClient.java when SelfHealingLocator runs out of fallbacks.
// Receives the failed locator + page HTML and returns a CSS/XPath suggestion.
function buildLocatorSuggestion(failedLocator, pageHtml) {
  // Simple heuristic: look for common patterns near the failed locator's hint
  // In a real integration Claude Desktop would answer this — here we provide
  // deterministic fallbacks so tests work even without Claude Desktop open.

  // Extract the attribute value from the failed locator string
  // e.g. "By.id: email"  →  "email"
  const hint = failedLocator.replace(/^By\.\w+:\s*/i, "").replace(/['"]/g, "").trim();

  // Try to find elements in the HTML whose id, name, or class contains the hint
  const candidates = [];

  // id= matches
  const idRe = new RegExp(`id=["']([^"']*${hint}[^"']*)["']`, "gi");
  let m;
  while ((m = idRe.exec(pageHtml)) !== null) candidates.push(`id::${m[1]}`);

  // name= matches
  const nameRe = new RegExp(`name=["']([^"']*${hint}[^"']*)["']`, "gi");
  while ((m = nameRe.exec(pageHtml)) !== null) candidates.push(`css::[name="${m[1]}"]`);

  // data-testid= matches
  const dtRe = new RegExp(`data-testid=["']([^"']*${hint}[^"']*)["']`, "gi");
  while ((m = dtRe.exec(pageHtml)) !== null) candidates.push(`css::[data-testid="${m[1]}"]`);

  if (candidates.length > 0) {
    process.stderr.write(`[suggest-locator] Hint "${hint}" → ${candidates[0]}\n`);
    return candidates[0];
  }

  process.stderr.write(`[suggest-locator] No candidate found for hint "${hint}"\n`);
  return null;
}

const healingServer = http.createServer((req, res) => {
  if (req.method === "POST" && req.url === "/suggest-locator") {
    let body = "";
    req.on("data", chunk => { body += chunk; });
    req.on("end", () => {
      try {
        const { failedLocator = "", pageHtml = "" } = JSON.parse(body);
        const suggestion = buildLocatorSuggestion(failedLocator, pageHtml);
        res.writeHead(200, { "Content-Type": "application/json" });
        res.end(JSON.stringify({ suggestion: suggestion || "" }));
      } catch (e) {
        res.writeHead(400, { "Content-Type": "application/json" });
        res.end(JSON.stringify({ error: e.message }));
      }
    });
  } else if (req.method === "GET" && req.url === "/health") {
    res.writeHead(200);
    res.end("ok");
  } else {
    res.writeHead(404);
    res.end("not found");
  }
});

healingServer.listen(HEALING_PORT, "127.0.0.1", () => {
  process.stderr.write(`[REST] Self-healing endpoint ready on http://127.0.0.1:${HEALING_PORT}/suggest-locator\n`);
});

// ── MCP SERVER ────────────────────────────────────────────────────────────────

const server = new Server(
  { name: "capstone-mcp-server", version: "1.0.0" },
  { capabilities: { tools: {} } }
);

server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: [
    {
      name: "list_project_structure",
      description: "Lists all files in the HybridNotesFramework project. Use ext='.java' to filter.",
      inputSchema: {
        type: "object",
        properties: {
          ext: { type: "string", description: "File extension filter, e.g. '.java'" },
          dir: { type: "string", description: "Subdirectory relative to project root" },
        },
      },
    },
    {
      name: "read_file",
      description: "Reads any file from the project by its path (relative to project root or absolute).",
      inputSchema: {
        type: "object",
        properties: {
          file_path: { type: "string", description: "e.g. 'src/test/java/com/notesapp/tests/ui/LoginTest.java'" },
        },
        required: ["file_path"],
      },
    },
    {
      name: "write_file",
      description: "Creates or overwrites a file in the project. Directories are created automatically.",
      inputSchema: {
        type: "object",
        properties: {
          file_path: { type: "string" },
          content:   { type: "string" },
        },
        required: ["file_path", "content"],
      },
    },
    {
      name: "generate_test_script",
      description:
        "Generates a complete Java TestNG test class from a plain-English description and writes it to the correct package (com.notesapp.tests.*). Use test_type='ui', 'api', or 'e2e'.",
      inputSchema: {
        type: "object",
        properties: {
          description:      { type: "string", description: "What the test should do" },
          test_type:        { type: "string", enum: ["ui", "api", "e2e"] },
          class_name:       { type: "string", description: "Java class name, e.g. 'DeleteNoteNegativeTest'" },
          write_to_project: { type: "boolean" },
        },
        required: ["description", "class_name"],
      },
    },
    {
      name: "execute_tests",
      description: "Runs mvn clean test in the project. Can filter by class, group, or suite XML.",
      inputSchema: {
        type: "object",
        properties: {
          filter:   { type: "string", description: "Test class filter, e.g. 'LoginTest'" },
          suite:    { type: "string", description: "TestNG suite XML, e.g. 'testng.xml'" },
          group:    { type: "string", description: "TestNG group, e.g. 'ui' or 'api'" },
          headless: { type: "boolean", description: "Run browser headless. Default: true" },
        },
      },
    },
    {
      name: "get_test_results",
      description: "Reads the latest test results from Surefire and Allure reports.",
      inputSchema: {
        type: "object",
        properties: {
          format: { type: "string", enum: ["summary", "full"] },
        },
      },
    },
    {
      name: "list_test_classes",
      description: "Lists all Java test class files in src/test/java.",
      inputSchema: { type: "object", properties: {} },
    },
  ],
}));

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;
  let result;
  try {
    switch (name) {
      case "list_project_structure": result = listProjectStructure(args); break;
      case "read_file":              result = readFile(args);              break;
      case "write_file":             result = writeFile(args);             break;
      case "generate_test_script":   result = generateTestScript(args);   break;
      case "execute_tests":          result = executeTests(args);          break;
      case "get_test_results":       result = getTestResults(args);        break;
      case "list_test_classes":      result = listTestClasses();           break;
      default:                       result = `Unknown tool: ${name}`;
    }
  } catch (e) {
    result = `Tool error: ${e.message}\n${e.stack}`;
  }
  return { content: [{ type: "text", text: String(result) }] };
});

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  process.stderr.write("Capstone MCP Server running (stdio + REST :3000)\n");
}

main().catch((e) => {
  process.stderr.write(`Fatal: ${e.message}\n`);
  process.exit(1);
});
